from pathlib import Path

import pytest

from alayout.adb import ADB_NAME, AdbError, find_adb


def make_sdk(root: Path) -> Path:
    tools = root / "platform-tools"
    tools.mkdir(parents=True)
    adb = tools / ADB_NAME
    adb.write_bytes(b"")
    return adb


def no_which(_name):
    return None


def test_explicit_file_wins(tmp_path):
    explicit = make_sdk(tmp_path / "explicit")
    make_sdk(tmp_path / "home")
    env = {"ANDROID_HOME": str(tmp_path / "home")}
    assert find_adb(str(explicit), env=env, cwd=tmp_path, which=no_which) == explicit


def test_explicit_directory_is_searched(tmp_path):
    adb = make_sdk(tmp_path / "sdk")
    assert find_adb(str(adb.parent), env={}, cwd=tmp_path, which=no_which) == adb


def test_explicit_missing_is_an_error(tmp_path):
    with pytest.raises(AdbError, match="adb not found at"):
        find_adb(str(tmp_path / "nope"), env={}, cwd=tmp_path, which=no_which)


def test_android_home_beats_local_properties(tmp_path):
    home_adb = make_sdk(tmp_path / "home")
    make_sdk(tmp_path / "props")
    (tmp_path / "local.properties").write_text(
        f"sdk.dir={(tmp_path / 'props').as_posix()}\n", encoding="utf-8")
    env = {"ANDROID_HOME": str(tmp_path / "home")}
    assert find_adb(env=env, cwd=tmp_path, which=no_which) == home_adb


def test_android_sdk_root_used_when_home_unset(tmp_path):
    adb = make_sdk(tmp_path / "root")
    assert find_adb(env={"ANDROID_SDK_ROOT": str(tmp_path / "root")}, cwd=tmp_path, which=no_which) == adb


def test_local_properties_with_escaped_windows_path_in_parent_dir(tmp_path):
    adb = make_sdk(tmp_path / "My Sdk")
    project = tmp_path / "proj"
    module = project / "app" / "src"
    module.mkdir(parents=True)
    escaped = str(tmp_path / "My Sdk").replace("\\", "\\\\").replace(":", "\\:")
    (project / "local.properties").write_text(
        f"## This file is automatically generated\nsdk.dir={escaped}\n", encoding="utf-8")
    assert find_adb(env={}, cwd=module, which=lambda _n: "/usr/bin/adb") == adb


def test_path_used_when_no_sdk_configured(tmp_path):
    assert find_adb(env={}, cwd=tmp_path, which=lambda n: f"/usr/bin/{n}") == Path("/usr/bin/adb")


def test_default_localappdata_sdk_is_last_resort(tmp_path):
    adb = make_sdk(tmp_path / "Android" / "Sdk")
    assert find_adb(env={"LOCALAPPDATA": str(tmp_path)}, cwd=tmp_path, which=no_which) == adb


def test_not_found_lists_what_was_tried(tmp_path):
    with pytest.raises(AdbError) as exc:
        find_adb(env={"ANDROID_HOME": str(tmp_path / "missing")}, cwd=tmp_path, which=no_which)
    message = str(exc.value)
    assert "adb not found" in message
    assert "missing" in message
    assert "--adb" in message
